### ISSUE TITLE
Consider parsing expression grammars

### ISSUE THREAD

**Issue by davegomez** [gosub-browser/gosub-engine#13]
I not sure if you are aware (you might) about **parsing expression grammars** to parse the HTML or other type of code, since they offer better performance and less space for errors than using Regex.

One library you can check is [pest](https://pest.rs).

You could also consider [html5ever](https://github.com/servo/html5ever) and [rust-cssparser](https://github.com/servo/rust-cssparser). They are part of the [servo](https://github.com/servo) project and are very mature already.

**Comment by jaytaph** [comment]
I've looked into different ways of parsing the html5. I think there are better ways then we have now, so I'm always open for idea's and suggestions.

I've also looked at some other (rust) html5parser projects but my intention is to create as much as possible ourselves. This doesn't mean we will be writing everything, and for a lot of things should use existing libraries, but as an html parser is the basis of a browser engine, I'd rather write it from scratch instead of using an existing one.

If you are willing to write some small example code on how a PEG parser should be incorporated, i'm happy to take a look at it to see if we could incorporate it, but the main focus I currently have is getting the current system running correctly.

**Comment by emwalker** [comment]
Related question (and possible answer) [here](https://github.com/jaytaph/gosub-browser/discussions/48#discussioncomment-7128407).

**Comment by davegomez** [comment]
And this is an example of the grammar for a functional HTML parser using pest.

https://docs.rs/crate/html_parser/latest/source/src/grammar/rules.pest

**Comment by jaytaph** [comment]
The current parser of both the CSS3 and HTML5 seems to work fine at the moment. No need to change to another system for now.
