### ISSUE TITLE
(Question) What package contain the bins?

### ISSUE THREAD

**Issue by hardBSDk** [gosub-browser/gosub-engine#489]
There's no `[[bin]]` section on the workspace package.

**Comment by Sharktheone** [comment]
The bins are in the workspace package. There is no `[[bin]]` section in the root `Cargo.toml` since rust creates them automatically when you put them into `src/bin/`.

You can run them normally via cargo `cargo run --bin renderer file://src/bin/resources/gosub.html`

**Comment by hardBSDk** [comment]
@Sharktheone I asked this because I'm packaging this program, thus I can't use `cargo run`

**Comment by Sharktheone** [comment]
Oh... okay... then you can use `cargo build --bin renderer -r` to build in release mode and then execute the standalone binary in `target/release/renderer`

Note that we can't even correctly render most websites, indeed we are *very very* far from correct... Most websites probably also only show back a black screen, since expanding shorthand css properties doesn't work.

**Comment by hardBSDk** [comment]
@Sharktheone That's enough, thanks!
