### ISSUE TITLE
Update node_id to use pub(crate)

### ISSUE THREAD

**Issue by jaytaph** [gosub-browser/gosub-engine#88]
See conversation:

https://github.com/jaytaph/gosub-browser/pull/80#pullrequestreview-1655123562

![image](https://github.com/jaytaph/gosub-browser/assets/241458/48aad7ee-a56f-4f13-b20c-e122fe562813)

**Comment by manish7017** [comment]
Maybe we should consider updating the visibility of all NodeID instances to pub(crate). This is because the codebase currently relies on NodeID being pub, and changing it to pub(crate) would break this dependency. However, before we proceed with this change, we need to ensure that it won’t introduce any unforeseen issues. Let’s discuss this further.

**Comment by blaumeise20** [comment]
I think this got misunderstood, I was talking about the field inside which has been made public, not the entire struct.
```rs
pub struct NodeId(pub(crate) usize);
```
